name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
      - name: ruby環境セットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: テスト実行
        run: rails test
